# Generated by Django 4.2.13 on 2024-05-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('club_time', models.CharField(max_length=100)),
                ('club_introduction', models.CharField(max_length=100)),
                ('club_details', models.CharField(max_length=100)),
                ('club_contact', models.CharField(max_length=100)),
                ('club_open', models.BooleanField()),
                ('club_open_start', models.DateField(max_length=100)),
                ('club_open_end', models.DateField(max_length=100)),
                ('club_code', models.CharField(max_length=100)),
                ('club_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
